/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general-purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    checkstyle
    java
    id("com.diffplug.spotless") version "8.10.1"
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("data"))
        }
        resources {
            setSrcDirs(listOf("data"))
        }
    }
}

tasks.withType(Checkstyle::class.java).configureEach {
    minHeapSize = "200m"
    maxHeapSize = "4g"
    maxWarnings = 0  // Fail on any warning
    maxErrors = 0    // Fail on any error
    source(project.sourceSets.main.get().allSource.matching {
        exclude("**/*.psd", "**/*.PSD")
    })
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

// Hygiene checks for the text data files: trailing whitespace and a final newline, the two things .editorconfig
// already asks every editor for. `./gradlew spotlessCheck` reports every violation in one run; `./gradlew
// spotlessApply` fixes them all. The Checkstyle workflow runs the check as its first step on every PR.
// Same setup as MegaMek, MegaMekLab and MekHQ, minus the Java import rules that do not apply here.
spotless {
    // Checked explicitly by CI rather than as part of `build`, so a plain build stays fast and works in a shallow
    // checkout that has no origin/main to ratchet against.
    isEnforceCheck = false

    // Until the whole tree has been formatted once, only look at files that differ from origin/main. Pass
    // -PspotlessFullTree to format everything (used for the one-time reformat and to measure it).
    if (!project.hasProperty("spotlessFullTree")) {
        ratchetFrom("origin/main")
    }

    format("data") {
        // Every text format in the tree except .blk (below). Images, fonts, sounds and archives are left alone.
        target(
            "data/**/*.txt", "data/**/*.yml", "data/**/*.yaml", "data/**/*.json", "data/**/*.xml",
            "data/**/*.csv", "data/**/*.mtf", "data/**/*.board", "data/**/*.mms",
            "data/**/*.tileinc", "data/**/*.mul", "data/**/*.xsd", "data/**/*.md",
            "*.md", "*.kts", "config/**/*.xml"
        )
        trimTrailingWhitespace()
        endWithNewline()
    }

    // The BLK writer in MegaMek ends every unit file with a blank line (6,719 of the 6,722 in the tree), so the
    // final-newline rule would fight MegaMekLab on every saved unit. Only trailing whitespace is checked here.
    format("blk") {
        target("data/**/*.blk")
        trimTrailingWhitespace()
    }
}

var stagingFolder = File(project.layout.buildDirectory.get().toString(), "staging")

dependencies {
    implementation("com.puppycrawl.tools:checkstyle:13.4.0")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// mm-data only produces the zipped artifacts (unit files, RATs, planetary systems)
// that the consuming projects (MegaMek, MegaMekLab, MekHQ) substitute for the loose
// source files. The consumers' own `stageDataFiles` tasks now copy the remaining
// loose data directly out of `mm-data/data`, so there is no intermediate staging
// copy here. Removing that copy avoids moving ~900 MB of image/board data twice per
// build; see each consumer's build.gradle for the split, incremental sync tasks.

tasks.register<Zip>("unitFilesZip") {
    description = "Creates zip archives of all the unit file folders (excluding loose .txt, .xml and .csv files)."
    group = "build"
    destinationDirectory.set(File(stagingFolder, "mekfiles"))
    archiveFileName.set("unit_files.zip")
    from("data/mekfiles") {
        exclude("*.txt")
        exclude("*.xml")
        exclude("*.csv")
        exclude("*.cache")
    }
}

tasks.register<Zip>("ratZip") {
    description = "Creates a zip archive of all the random assignment tables."
    group = "build"
    from("data/rat")
    destinationDirectory.set(File(stagingFolder, "rat"))
    archiveFileName.set("rat_default.zip")
}

tasks.register<Zip>("canonSystemZip") {
    description = "Creates a zip archive of canon planetary systems."
    group = "build"
    from("data/universe/planetary_systems/canon_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("canon_systems.zip")
}

tasks.register<Zip>("connectorSystemZip") {
    description = "Creates a zip archive of connector systems planetary systems."
    group = "build"
    from("data/universe/planetary_systems/connector_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("connector_systems.zip")
}
