"""Named vehicle MiniMeks: one builder function per vehicle, registered in VEHICLE_BUILDERS.

`unit_vehicle_models.py` builds every vehicle listed in unit-models/vehicles.json as part of the modular export
(build_modular_unit_models.py). The BattleTech Unit Viewer drafts new builders into this file.

A builder draws on MegaMek's ground-vehicle rig (vehicle-v1), the same nodes as the generic bodies:
`hull` (the root of the body), `leftDrive`/`rightDrive` for tracks or wheels, and `turret` (plus `turret2`
for a front turret), which MegaMek turns with the turret and hides on a variant without one. Axes: +x right,
+y forward, +z up; the ground is z 0 and every vehicle is authored 52 units long (MegaMek resizes by size
class). Each vehicle's recipe (mode, sprite, weapon scale, turret socket) is in unit-models/vehicles.json.

The viewer adds generated builders between marker comments above the anchor line below; refine them by hand.
"""

from math import atan2, cos, pi, sin

from unit_mek_chassis import forward, upright  # noqa: F401 - shape helpers for hand-refined builders


# --- MiniMek draft manticore: generated by the BattleTech Unit Viewer; refine by hand ---
def manticore(g):
    # Manticore Heavy Tank: shapes from the line art, proportions from the mini, overall size from the HBS model.
    # A low hull between two heavy segmented track skirts, and a wide faceted turret set well back on the deck.
    g.joint('hull', (0, 0, 8))
    g.joint('leftDrive', (-16, 0, 4), 'hull')
    g.joint('rightDrive', (16, 0, 4), 'hull')
    # The turret node turns with the turret in game, and is hidden on a variant without one.
    g.joint('turret', (0, -8.5, 13.3), 'hull')

    def ring(y, left, right, bottom, top, cut):
        # One octagonal cross-section across the tank at `y`: top edge, right side, bottom, left side.
        return [(left+cut, y, top), (right-cut, y, top), (right, y, top-cut), (right, y, bottom+cut),
                (right-cut, y, bottom), (left+cut, y, bottom), (left, y, bottom+cut), (left, y, top-cut)]

    # Hull: a low deck between the skirts, with a raised rear deck behind the turret.
    g.loft([ring(-26, -12, 12, 3.5, 12.5, 1.2), ring(-24.8, -12.2, 12.2, 2.6, 14, 1.2),
            ring(-22, -12.2, 12.2, 2.6, 14, 1.2), ring(-21, -12.2, 12.2, 2.6, 13.3, 1.2),
            ring(13.2, -12.2, 12.2, 2.6, 13.3, 1.2)], 'hull')
    # The front is not a plain glacis. From the bottom up: the underside sits back, a chin juts forward, a sloped
    # plate runs up and back from it, and the grille box juts forward again over the top of the slope, its top
    # running back as the deck the turret sits on.
    g.loft([ring(13, -11.6, 11.6, 2.6, 9.4, .8), ring(18.3, -11.2, 11.2, 2.6, 5.2, .6),
            ring(19.2, -10.8, 10.8, 3.2, 4.6, .4)], 'hull')
    # The grille leans forward: its top edge overhangs by 2 and its face slopes back and down to the base.
    g.loft([ring(13, -11.8, 11.8, 9.4, 13.3, .8), ring(14, -11.8, 11.8, 9.4, 13.3, .8),
            ring(16, -11.4, 11.4, 12.6, 13.3, .3)], 'hull')
    # Four exhausts across the rear plate, like a modern main battle tank's: a dark louvre with two bars over it.
    for across in (-7.5, -2.5, 2.5, 7.5):
        g.face([(across+1.8, -26.03, 8.2), (across+1.8, -26.03, 11), (across-1.8, -26.03, 11), (across-1.8, -26.03, 8.2)],
               'hull', 'dark')
        for height in (9.1, 10.1):
            g.box((across, -26.1, height), (3.8, .3, .3), 'hull', 'metal')
    # Slats across the grille's sloped face.
    def on_face(z):
        return 14.02 + (z-9.4)*2/3.2
    for index in range(5):
        left = -8.8+index*3.8
        g.face([(left, on_face(10.2), 10.2), (left, on_face(12), 12), (left+1.8, on_face(12), 12),
                (left+1.8, on_face(10.2), 10.2)], 'hull', 'dark')
    # The deck flares out over the skirts: from the back of the grille it angles out to the middle of each skirt,
    # then runs straight back almost to the rear. Its outer top edge is bevelled.
    for side in (-1, 1):
        plan = [(-16, -23), (-12.2, -23), (-12.2, 13.8), (-16, 2.2)]
        bevelled = [(-15.2, -23), (-12.2, -23), (-12.2, 13.8), (-15.2, 4.6)]
        rings = [[(x*side, y, z) for x, y in outline] for z, outline in ((9.4, plan), (12.5, plan), (13.3, bevelled))]
        # Wound anticlockwise seen from above; mirroring to the right side flips that, so reverse it there.
        g.loft(rings if side < 0 else [list(reversed(ring)) for ring in rings], 'hull')
        # Vent slats along the flare's angled face, ahead of the turret.
        for index in range(5):
            near, far = .1+index*.17, .21+index*.17
            quad = [((12.2+3.8*t)*side + .03*side*.95, 13.8-11.6*t + .03*.31, z)
                    for t, z in ((near, 10.3), (near, 12.2), (far, 12.2), (far, 10.3))]
            g.face(quad if side > 0 else list(reversed(quad)), 'hull', 'dark')

    # Track skirts: four armour segments per side over the top two-thirds of the track, the front one
    # turned up into a nose that reaches past the hull. A dark track strip runs underneath.
    for side, node in ((-1, 'leftDrive'), (1, 'rightDrive')):
        inner, outer = 12.2*side, 19.8*side
        left, right = min(inner, outer), max(inner, outer)
        for rear, front in ((-26, -12.2), (-11.9, 2), (2.3, 15.5)):
            g.loft([ring(rear, left, right, 2.2 if rear > -26 else 3.4, 9.4 if rear > -26 else 8.6, .9),
                    ring(front, left, right, 2.2, 9.4, .9)], node)
        g.loft([ring(15.8, left, right, 2.2, 9.4, .9), ring(21, left, right, 2.2, 9.4, .9),
                ring(24, left, right, 3.8, 8.6, .9), ring(26, left, right, 5.2, 7.9, .7)], node)
        # The groove band along each skirt's outer face, as in the side art.
        face_x = outer + .03*side
        for rear, front in ((-25.5, -12.2), (-11.9, 2), (2.3, 15.5)):
            band = [(face_x, rear, 4.8), (face_x, front, 4.8), (face_x, front, 5.6), (face_x, rear, 5.6)]
            g.face(band if side > 0 else list(reversed(band)), node, 'dark')
        # The track: a loop under the skirt, flat along the ground and rounding up into the skirt at each end,
        # which stops short of the skirt's upturned nose and its rear.
        track_left, track_right = min(13*side, 19*side), max(13*side, 19*side)
        g.loft([[(track_left, y, top), (track_right, y, top), (track_right, y, bottom), (track_left, y, bottom)]
                for y, bottom, top in ((-24.6, 1.9, 2.6), (-24.2, .9, 2.6), (-23.4, .3, 2.6), (-22.3, 0, 2.6),
                                       (19, 0, 2.6), (20.1, .3, 2.6), (20.6, .9, 2.6), (20.9, 1.9, 2.6))],
               node, 'dark')

    # Turret: wide, tall and faceted, narrowing to angled cheeks at the front, set back by half the deck behind it
    # so the long main gun reaches out over the hull.
    def turret_ring(y, half, top_half, bottom_half, bottom, top):
        return [(-top_half, y, top), (top_half, y, top), (half, y, top-1.8), (half, y, bottom+1.2),
                (bottom_half, y, bottom), (-bottom_half, y, bottom), (-half, y, bottom+1.2), (-half, y, top-1.8)]

    g.loft([turret_ring(-20, 9.5, 7, 8, 13.8, 19.8), turret_ring(-17.5, 11.75, 8.5, 9.5, 13.3, 20.8),
            turret_ring(-4.5, 11.75, 8.5, 9.5, 13.3, 20.8), turret_ring(-.5, 10.5, 7.5, 8.5, 13.5, 20.4),
            turret_ring(3, 6.5, 4.5, 5, 14.2, 19.4)], 'turret')
    # The gun housing: a long armoured box reaching forward from the middle of the turret front over the main gun's
    # root, the barrel leaving from its front.
    g.box((0, 6.6, 17.2), (5, 8, 4.2), 'turret', bevel=.2)
    # A vent grille at the back of each turret side.
    for index in range(3):
        start = -17.3+index*1.1
        g.face([(-11.8, start, 16.4), (-11.8, start, 18.9), (-11.8, start+.7, 18.9), (-11.8, start+.7, 16.4)],
               'turret', 'dark')
        g.face([(11.8, start+.7, 16.4), (11.8, start+.7, 18.9), (11.8, start, 18.9), (11.8, start, 16.4)],
               'turret', 'dark')
    # The dome in the middle of the roof.
    upright(g, [(20.7, 9, 9, 0, -10), (22.3, 7.5, 7.5, 0, -10), (23.2, 4.5, 4.5, 0, -10)], 'turret')
    # The swivel post at the back of the roof that carries the raised long-range launcher.
    g.box((-3, -16, 22), (3.2, 3.2, 3.2), 'turret', bevel=.3)
# --- end of MiniMek draft manticore ---


# --- MiniMek draft manticore-ii: generated by the BattleTech Unit Viewer; refine by hand ---
def manticore_ii(g):
    # Manticore II Heavy Tank, the 70-ton successor, drawn from its line art with the Manticore filling the gaps.
    # Bulkier than the Manticore: tall slab sides cover the tracks almost to the ground and meet a high flat deck,
    # the nose is blunt and stepped, and a low, long, rounded turret carries a launcher drum on each side.
    g.joint('hull', (0, 0, 8))
    g.joint('leftDrive', (-16.5, 0, 6), 'hull')
    g.joint('rightDrive', (16.5, 0, 6), 'hull')
    # The turret node turns with the turret in game, and is hidden on a variant without one.
    g.joint('turret', (0, -8.5, 16.8), 'hull')

    def ring(y, left, right, bottom, top, cut):
        # One octagonal cross-section across the tank at `y`: top edge, right side, bottom, left side.
        return [(left+cut, y, top), (right-cut, y, top), (right, y, top-cut), (right, y, bottom+cut),
                (right-cut, y, bottom), (left+cut, y, bottom), (left, y, bottom+cut), (left, y, top-cut)]

    def disc(x, y, bottom, top, radius, node, material='paint'):
        # A short upright eight-sided cylinder: hatches, exhaust caps.
        upright(g, [(bottom, 2*radius, 2*radius, x, y), (top, 2*radius, 2*radius, x, y)], node, material, cut=.3)

    # Hull between the slab sides, its deck level with their tops. The nose is set back between them: the deck
    # breaks into a glacis, then a short upright lip carries four lamp ports.
    g.loft([ring(-26, -12.8, 12.8, 3.5, 11.8, 1.2), ring(-25, -12.8, 12.8, 2.6, 12.5, 1.2),
            ring(15, -12.8, 12.8, 2.6, 12.5, 1.2), ring(18.5, -12.4, 12.4, 2.6, 7.5, .8),
            ring(20, -12, 12, 3.4, 7, .5)], 'hull')
    for across in (-7.5, -2.5, 2.5, 7.5):
        g.face([(across-.8, 20.02, 4.6), (across-.8, 20.02, 5.8), (across+.8, 20.02, 5.8), (across+.8, 20.02, 4.6)],
               'hull', 'dark')
    # The raised centre deck between the slab sides: from their inner edges the hull curves up to a flat top 4.3
    # higher and about 16 wide, running from the rear plate to the glacis, where it slopes down. The turret sits
    # on it.
    def raised(y, top):
        rise = top - 12.4
        return [(-7.9, y, top), (7.9, y, top), (10.6, y, 12.4+rise*.72), (12.4, y, 12.4+rise*.12), (12.6, y, 12.4),
                (-12.6, y, 12.4), (-12.4, y, 12.4+rise*.12), (-10.6, y, 12.4+rise*.72)]
    g.loft([raised(-25.8, 16.1), raised(-25, 16.8), raised(12.8, 16.8), raised(15.2, 12.9)], 'hull')
    # Round hatches on the raised deck, ahead of the turret, and the sensor dome at its front right corner.
    disc(-4, 9.5, 16.7, 17.1, 1.7, 'hull', 'edge')
    disc(3, 10, 16.7, 17.1, 1.5, 'hull', 'edge')
    upright(g, [(16.6, 3, 3, 8.2, 11.4), (18, 3, 3, 8.2, 11.4), (18.8, 1.8, 1.8, 8.2, 11.4)], 'hull', 'edge')
    # Four exhaust louvres across the rear plate.
    for across in (-7.5, -2.5, 2.5, 7.5):
        g.face([(across+1.8, -26.03, 7.4), (across+1.8, -26.03, 10.2), (across-1.8, -26.03, 10.2),
                (across-1.8, -26.03, 7.4)], 'hull', 'dark')

    # Slab sides: four flat armour panels per side almost to the ground, a long vent slot high on each, and a
    # blunt chamfered front. The track shows only as a strip underneath.
    panels = ((-25.8, -13.7), (-13.3, -1.2), (-.8, 11.3), (11.7, 19))
    for side, node in ((-1, 'leftDrive'), (1, 'rightDrive')):
        inner, outer = 12.6*side, 20.5*side
        left, right = min(inner, outer), max(inner, outer)
        for rear, front in panels:
            low, high = (1.8, 12) if rear < -25 else (1.2, 12.5)
            g.loft([ring(rear, left, right, low, high, 1), ring(front, left, right, 1.2, 12.5, 1)], node)
            face_x = outer + .03*side
            slot = [(face_x, rear+1.2, 9.8), (face_x, front-1.2, 9.8), (face_x, front-1.2, 10.6),
                    (face_x, rear+1.2, 10.6)]
            g.face(slot if side > 0 else list(reversed(slot)), node, 'dark')
        # The blunt front: the outer edge draws in and the top and bottom close toward it.
        drawn_in = outer - .7*side
        g.loft([ring(19, left, right, 1.2, 12.5, 1),
                ring(22, min(inner, drawn_in), max(inner, drawn_in), 2.2, 11.8, 1),
                ring(23.5, min(inner, outer - 1.5*side), max(inner, outer - 1.5*side), 3.6, 10.8, .8)], node)
        track_left, track_right = min(13*side, 20*side), max(13*side, 20*side)
        g.loft([[(track_left, y, top), (track_right, y, top), (track_right, y, bottom), (track_left, y, bottom)]
                for y, bottom, top in ((-24.6, 1.9, 2.6), (-24.2, .9, 2.6), (-23.4, .3, 2.6), (-22.3, 0, 2.6),
                                       (19, 0, 2.6), (20.1, .3, 2.6), (20.6, .9, 2.6), (20.9, 1.9, 2.6))],
               node, 'dark')
    # A raised hump over the rear of each side's armour, its top sloping down and out, with three round caps set
    # into the slope, each with a dark slot across it.
    def clockwise(points):
        # Ordered clockwise in x and z about their centre, as the lofts across the tank expect.
        centre_x = sum(x for x, _ in points)/len(points)
        centre_z = sum(z for _, z in points)/len(points)
        return sorted(points, key=lambda point: -atan2(point[1]-centre_z, point[0]-centre_x))

    for side, node in ((-1, 'leftDrive'), (1, 'rightDrive')):
        inner, outer = 12.8*side, 19.8*side
        crest, eave = (14.3*side, 15.2), (outer, 13.2)

        def hump(y, drop):
            return [(x, y, z) for x, z in clockwise([(inner, 12.4), (outer, 12.4), (eave[0], eave[1]-drop),
                                                     (crest[0], crest[1]-drop), (inner, crest[1]-drop)])]
        g.loft([hump(-25.2, 1.4), hump(-23.8, 0), hump(-13, 0), hump(-11.5, 1.6)], node)
        slope_x, slope_z = eave[0]-crest[0], eave[1]-crest[1]
        length = (slope_x**2 + slope_z**2)**.5
        normal = (-slope_z*side/length, 0, abs(slope_x)/length)
        across = (-normal[2], 0, normal[0])
        for along in (-22, -18.5, -15):
            centre = ((crest[0]+eave[0])/2 + normal[0]*.02, along, (crest[1]+eave[1])/2 + normal[2]*.02)

            def cap_ring(lift, radius=1.3):
                return [(centre[0] + normal[0]*lift + radius*(sin(turn)*across[0]), centre[1] + radius*cos(turn),
                         centre[2] + normal[2]*lift + radius*sin(turn)*across[2])
                        for turn in (2*pi*i/6 for i in range(6))]
            g.loft([cap_ring(-.1), cap_ring(.5)], node)
            top = [(centre[0] + normal[0]*.52 + v*across[0], centre[1] + u, centre[2] + normal[2]*.52 + v*across[2])
                   for u, v in ((-.8, -.2), (.8, -.2), (.8, .2), (-.8, .2))]
            g.face(top, node, 'dark')

    # Turret: low, long and rounded - softer shoulders than the Manticore's facets - set back on the raised deck,
    # its crown rising along the middle.
    def turret_ring(y, half, bottom, top, crown):
        tall = top - bottom
        return [(-half*.3, y, top+crown), (half*.3, y, top+crown), (half*.72, y, top), (half, y, top-tall*.45),
                (half*.92, y, bottom+tall*.15), (half*.75, y, bottom), (-half*.75, y, bottom),
                (-half*.92, y, bottom+tall*.15), (-half, y, top-tall*.45), (-half*.72, y, top)]

    g.loft([turret_ring(-22, 7, 17.1, 20.7, .6), turret_ring(-19.5, 9.6, 16.8, 21.9, 1.4),
            turret_ring(-3, 10, 16.8, 22.1, 1.6), turret_ring(1.5, 8.5, 16.9, 21.5, 1.2),
            turret_ring(4.5, 5.5, 17.3, 20.5, .5)], 'turret')
    # The gun housing at the middle of the turret front; the Heavy PPC leaves from its front.
    g.box((0, 5.8, 19.3), (4.4, 5, 3.8), 'turret', bevel=.2)
    # The domed hatch ring on the roof.
    upright(g, [(23.3, 4.8, 4.8, -2.5, -13), (24.1, 4.8, 4.8, -2.5, -13), (24.5, 3.2, 3.2, -2.5, -13)], 'turret')
    # Vent slats on the front cheeks.
    for index in range(3):
        start = -2.6+index*.9
        g.face([(-9.75, start, 18.5), (-9.75, start, 20.1), (-9.75, start+.55, 20.1), (-9.75, start+.55, 18.5)],
               'turret', 'dark')
        g.face([(9.75, start+.55, 18.5), (9.75, start+.55, 20.1), (9.75, start, 20.1), (9.75, start, 18.5)],
               'turret', 'dark')
    # Grey saddles high on each rear shoulder, carrying the two box launchers.
    for side in (-1, 1):
        g.box((8.8*side, -14, 21.9), (3.6, 4.4, 1.6), 'turret', 'metal')
# --- end of MiniMek draft manticore-ii ---


# --- chassis builders (the BattleTech Unit Viewer adds generated ones above this line)

VEHICLE_BUILDERS = {
    'manticore': manticore,
    'manticore-ii': manticore_ii,
}
